from fpdf import FPDF
from typing import List, Dict
from datetime import datetime

class PDFService:
    """PDF export service"""
    
    def generate_report(self, query: str, results: List[Dict], title: str = "Research Report") -> bytes:
        """Generate PDF report"""
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 16)
        
        # Title
        pdf.cell(200, 10, txt=title, ln=True, align="C")
        pdf.ln(10)
        
        # Query info
        pdf.set_font("Arial", "", 12)
        pdf.cell(200, 10, txt=f"Research Topic: {query}", ln=True)
        pdf.cell(200, 10, txt=f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
        pdf.cell(200, 10, txt=f"Total Sources: {len(results)}", ln=True)
        pdf.ln(10)
        
        # Divider
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)
        
        # Results
        for i, r in enumerate(results, 1):
            pdf.set_font("Arial", "B", 12)
            pdf.multi_cell(200, 10, txt=f"{i}. {r.get('title', 'Untitled')[:80]}")
            
            pdf.set_font("Arial", "I", 10)
            pdf.cell(200, 8, txt=f"URL: {r.get('link', 'N/A')[:100]}", ln=True)
            
            if r.get('date'):
                pdf.cell(200, 8, txt=f"Date: {r.get('date')}", ln=True)
            
            if r.get('topic'):
                pdf.cell(200, 8, txt=f"Topic: {r.get('topic')} ({r.get('topic_confidence')})", ln=True)
            
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(200, 8, txt=f"Summary: {r.get('summary', 'N/A')[:250]}...")
            
            pdf.ln(5)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(5)
        
        # Footer
        pdf.set_font("Arial", "I", 8)
        pdf.cell(200, 10, txt="Generated by AI Research Assistant", ln=True, align="C")
        
        return pdf.output(dest="S").encode("latin-1")
    
    def generate_summary_report(self, query: str, summary: str) -> bytes:
        """Generate simple summary PDF"""
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 16)
        pdf.cell(200, 10, txt="Summary Report", ln=True, align="C")
        pdf.ln(10)
        
        pdf.set_font("Arial", "", 12)
        pdf.cell(200, 10, txt=f"Topic: {query}", ln=True)
        pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
        pdf.ln(10)
        
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(200, 10, txt=summary)
        
        return pdf.output(dest="S").encode("latin-1")

pdf_service = PDFService()